version: '3.8'
services:
  mysql:
    # 使用 MySQL 8.0.28 镜像
    image: mysql:8.0.28
    # 容器名称为 docker_mysql
    container_name: docker_mysql
    # 容器退出时自动重启
    restart: always
    # 防止被OOM kill, -1000为最低优先级
    oom_score_adj: -1000
    environment:
      # 设置 MySQL root 用户的密码为 root
      MYSQL_ROOT_PASSWORD: "blk@2024~NIUBI!mysql%mmm"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 63306:3306
    volumes:
      # 挂载数据目录
       - /etc/localtime:/etc/localtime
       - /opt/dockerstore/mysql/data:/var/lib/mysql
       - /opt/dockerstore/mysql/conf/my.cnf:/etc/mysql/my.cnf
       - /opt/dockerstore/mysql/log:/var/log/mysql
       - /opt/dockerstore/mysql/mysql-files:/var/lib/mysql-files
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci