---
- name: 修改用户密码
  hosts: all
  become: yes
  vars:
    username: "your_username"  # 在这里指定用户名
    password: "your_password"  # 在这里指定新密码

  tasks:
    - name: 打印修改的用户名和密码
      debug:
        msg: "将要修改用户 {{ username }} 的密码为 {{ password }}"

    - name: 修改用户密码
      shell: echo "{{ username }}:{{ password }}" | chpasswd
