- name: Setup and install Docker on managed nodes
  hosts: all
  become: yes
  vars:
    - source_path: /tmp/ansible
    - remote_path: /opt/ansible
  tasks:

    - name: Copy redis
      copy:
        src: "{{source_path}}/dockerstore/dockerfile/redis/"
        dest: "{{ remote_path }}/dockerstore/dockerfile/redis/"
        mode: '0755'
        owner: root
        group: root
        backup: yes
        #checksum: yes
      tags:
        - copy


    - name: Stop Docker Redis container if exists
      shell: docker stop docker_redis
      ignore_errors: yes

    - name: Remove Docker Redis container if exists
      shell: docker rm docker_redis
      ignore_errors: yes


    - name: Remove Docker Redis image if exists
      shell: docker rmi redis:6.0
      ignore_errors: yes
         
    - name: Run  script
      command: /bin/bash "{{ remote_path }}"/dockerstore/dockerfile/redis/install_redis.sh
      args:
        chdir: "{{ remote_path }}/dockerstore/dockerfile/redis/"
      async: 600
      poll: 10
      tags:
        - bash
